"""Out-of-band notice that a malformed ``ask_user`` answer was rejected.

This event is emitted on the user-message path (not generated by the agent) and
is intentionally **not** LLM-convertible: a corrective note placed in the LLM
stream would sit between the pending tool call and its eventual result, so the
resumed history would contain ``assistant tool_use`` -> ``user note`` ->
``tool_result``. Providers such as Anthropic require the tool result to directly
follow its tool call and reject that ordering. Keeping the notice outside the
LLM event stream lets clients surface the feedback while the pending request
stays open for a valid retry.
"""

from pydantic import Field

from openhands.sdk.event.base import Event
from openhands.sdk.event.types import SourceType


class AskUserAnswerNoticeEvent(Event):
    """A malformed answer was rejected while an ``ask_user`` call is pending."""

    source: SourceType = "environment"
    request_id: str = Field(
        description="Id of the pending ``ask_user`` request the answer targeted."
    )
    detail: str = Field(
        description="Human-readable reason the answer could not be used."
    )
