from __future__ import annotations

from pydantic import Field
from rich.text import Text

from openhands.sdk.event.base import Event, LLMConvertibleEvent
from openhands.sdk.event.types import EventID, SourceType
from openhands.sdk.llm import Message, TextContent


class Condensation(Event):
    """This action indicates a condensation of the conversation history is happening."""

    forgotten_event_ids: list[EventID] = Field(
        default_factory=list,
        description="The IDs of the events that are being forgotten "
        "(removed from the `View` given to the LLM).",
    )

    summary: str | None = Field(
        default=None, description="An optional summary of the events being forgotten."
    )

    summary_offset: int | None = Field(
        default=None,
        ge=0,
        description="An optional offset to the start of the resulting view (after"
        " forgotten events have been removed) indicating where the summary should be"
        " inserted. If not provided, the summary will not be inserted into the view.",
    )
    llm_response_id: EventID = Field(
        description=(
            "Completion or Response ID of the LLM response that generated this event"
        ),
    )

    source: SourceType = "environment"

    @property
    def visualize(self) -> Text:
        text = Text()

        text.append("Auto Conversation Condensation Triggered.\n", style="bold")

        text.append(f"Forgetting {len(self.forgotten_event_ids)} events\n")
        if self.summary:
            text.append("\n[Summary of Events Being Forgotten]\n", style="bold")
            text.append(f"{self.summary}\n")
        return text
    
    @property
    def summary_event(self) -> CondensationSummaryEvent | None:
        """Generates a CondensationSummaryEvent if a summary is present.

        Since summary events are not part of the main event store and are generated
        dynamically, this property ensures the created event has a unique and consistent
        ID based on the condensation event's ID.
        """
        if self.summary is None:
            return None
        
        return CondensationSummaryEvent(
            id=self.id + "-summary",
            summary=self.summary,
            source=self.source,
        )


class CondensationRequest(Event):
    """This action is used to request a condensation of the conversation history.

    Attributes:
        action (str): The action type, namely ActionType.CONDENSATION_REQUEST.
    """

    source: SourceType = "environment"

    @property
    def visualize(self) -> Text:
        text = Text()
        text.append("Conversation Condensation Requested\n", style="bold")
        message = (
            "A condensation of the conversation history has been requested to "
            "manage context window usage.\n"
        )
        text.append(message)
        return text


class CondensationSummaryEvent(LLMConvertibleEvent):
    """This event represents a summary generated by a condenser."""

    summary: str
    """The summary text."""

    source: SourceType = "environment"

    def to_llm_message(self) -> Message:
        return Message(
            role="user",
            content=[TextContent(text=self.summary)],
        )
