from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version
from typing import Any

from openhands.sdk._lazy_imports import import_lazy_symbol, lazy_dir
from openhands.sdk.banner import _print_banner


try:
    __version__ = version("openhands-sdk")
except PackageNotFoundError:
    __version__ = "0.0.0"  # fallback for editable/unbuilt environments

# Print the startup banner before importing the rest of the SDK surface.
_print_banner(__version__)

__all__ = [
    "LLM",
    "LLMRegistry",
    "LLMProfileStore",
    "LLMStreamChunk",
    "FallbackStrategy",
    "TokenCallbackType",
    "TokenUsage",
    "ConversationStats",
    "RegistryEvent",
    "Message",
    "TextContent",
    "ImageContent",
    "ThinkingBlock",
    "RedactedThinkingBlock",
    "Tool",
    "ToolDefinition",
    "AgentBase",
    "Agent",
    "Action",
    "Observation",
    "MCPClient",
    "MCPToolDefinition",
    "MCPToolObservation",
    "MessageEvent",
    "HookExecutionEvent",
    "create_mcp_tools",
    "get_logger",
    "Conversation",
    "BaseConversation",
    "LocalConversation",
    "RemoteConversation",
    "ConversationExecutionStatus",
    "ConversationCallbackType",
    "Event",
    "LLMConvertibleEvent",
    "AgentContext",
    "LLMSummarizingCondenser",
    "CondenserSettings",
    "ConversationSettings",
    "VerificationSettings",
    "ACPAgentSettings",
    "AgentSettings",
    "AgentSettingsConfig",
    "LLMAgentSettings",
    "default_agent_settings",
    "export_agent_settings_schema",
    "validate_agent_settings",
    "SettingsChoice",
    "SettingProminence",
    "SettingsFieldMetadata",
    "SettingsFieldSchema",
    "SettingsSchema",
    "SettingsSectionMetadata",
    "SettingsSectionSchema",
    "export_settings_schema",
    "field_meta",
    "FileStore",
    "LocalFileStore",
    "Plugin",
    "register_tool",
    "resolve_tool",
    "list_registered_tools",
    "Workspace",
    "LocalWorkspace",
    "RemoteWorkspace",
    "AsyncRemoteWorkspace",
    "register_agent",
    "load_project_agents",
    "load_user_agents",
    "load_agents_from_dir",
    "agent_definition_to_factory",
    "load_project_skills",
    "load_skills_from_dir",
    "load_user_skills",
    "page_iterator",
    "__version__",
]

_LAZY_IMPORTS = {
    "LLM": (".llm.llm", "LLM"),
    "LLMRegistry": (".llm.llm_registry", "LLMRegistry"),
    "LLMProfileStore": (".llm.llm_profile_store", "LLMProfileStore"),
    "LLMStreamChunk": (".llm.streaming", "LLMStreamChunk"),
    "FallbackStrategy": (".llm.fallback_strategy", "FallbackStrategy"),
    "TokenCallbackType": (".llm.streaming", "TokenCallbackType"),
    "TokenUsage": (".llm.utils.metrics", "TokenUsage"),
    "ConversationStats": (".conversation.conversation_stats", "ConversationStats"),
    "RegistryEvent": (".llm.llm_registry", "RegistryEvent"),
    "Message": (".llm.message", "Message"),
    "TextContent": (".llm.message", "TextContent"),
    "ImageContent": (".llm.message", "ImageContent"),
    "ThinkingBlock": (".llm.message", "ThinkingBlock"),
    "RedactedThinkingBlock": (".llm.message", "RedactedThinkingBlock"),
    "Tool": (".tool.spec", "Tool"),
    "ToolDefinition": (".tool.tool", "ToolDefinition"),
    "AgentBase": (".agent.base", "AgentBase"),
    "Agent": (".agent.agent", "Agent"),
    "Action": (".tool.schema", "Action"),
    "Observation": (".tool.schema", "Observation"),
    "MCPClient": (".mcp.client", "MCPClient"),
    "MCPToolDefinition": (".mcp.tool", "MCPToolDefinition"),
    "MCPToolObservation": (".mcp.definition", "MCPToolObservation"),
    "MessageEvent": (".event.llm_convertible", "MessageEvent"),
    "HookExecutionEvent": (".event.hook_execution", "HookExecutionEvent"),
    "create_mcp_tools": (".mcp.utils", "create_mcp_tools"),
    "get_logger": (".logger.logger", "get_logger"),
    "Conversation": (".conversation.conversation", "Conversation"),
    "BaseConversation": (".conversation.base", "BaseConversation"),
    "LocalConversation": (".conversation.impl.local_conversation", "LocalConversation"),
    "RemoteConversation": (
        ".conversation.impl.remote_conversation",
        "RemoteConversation",
    ),
    "ConversationExecutionStatus": (
        ".conversation.state",
        "ConversationExecutionStatus",
    ),
    "ConversationCallbackType": (".conversation.types", "ConversationCallbackType"),
    "Event": (".event.base", "Event"),
    "LLMConvertibleEvent": (".event.base", "LLMConvertibleEvent"),
    "AgentContext": (".context.agent_context", "AgentContext"),
    "LLMSummarizingCondenser": (
        ".context.condenser.llm_summarizing_condenser",
        "LLMSummarizingCondenser",
    ),
    "CondenserSettings": (".settings.model", "CondenserSettings"),
    "ConversationSettings": (".settings.model", "ConversationSettings"),
    "VerificationSettings": (".settings.model", "VerificationSettings"),
    "ACPAgentSettings": (".settings.model", "ACPAgentSettings"),
    "AgentSettings": (".settings.model", "AgentSettings"),
    "AgentSettingsConfig": (".settings.model", "AgentSettingsConfig"),
    "LLMAgentSettings": (".settings.model", "LLMAgentSettings"),
    "default_agent_settings": (".settings.model", "default_agent_settings"),
    "export_agent_settings_schema": (
        ".settings.model",
        "export_agent_settings_schema",
    ),
    "validate_agent_settings": (".settings.model", "validate_agent_settings"),
    "SettingsChoice": (".settings.model", "SettingsChoice"),
    "SettingProminence": (".settings.metadata", "SettingProminence"),
    "SettingsFieldMetadata": (".settings.metadata", "SettingsFieldMetadata"),
    "SettingsFieldSchema": (".settings.model", "SettingsFieldSchema"),
    "SettingsSchema": (".settings.model", "SettingsSchema"),
    "SettingsSectionMetadata": (
        ".settings.metadata",
        "SettingsSectionMetadata",
    ),
    "SettingsSectionSchema": (".settings.model", "SettingsSectionSchema"),
    "export_settings_schema": (".settings.model", "export_settings_schema"),
    "field_meta": (".settings.metadata", "field_meta"),
    "FileStore": (".io.base", "FileStore"),
    "LocalFileStore": (".io.local", "LocalFileStore"),
    "Plugin": (".plugin.plugin", "Plugin"),
    "register_tool": (".tool.registry", "register_tool"),
    "resolve_tool": (".tool.registry", "resolve_tool"),
    "list_registered_tools": (".tool.registry", "list_registered_tools"),
    "Workspace": (".workspace.workspace", "Workspace"),
    "LocalWorkspace": (".workspace.local", "LocalWorkspace"),
    "RemoteWorkspace": (".workspace.remote", "RemoteWorkspace"),
    "AsyncRemoteWorkspace": (".workspace.remote", "AsyncRemoteWorkspace"),
    "register_agent": (".subagent.registry", "register_agent"),
    "load_project_agents": (".subagent.load", "load_project_agents"),
    "load_user_agents": (".subagent.load", "load_user_agents"),
    "load_agents_from_dir": (".subagent.load", "load_agents_from_dir"),
    "agent_definition_to_factory": (
        ".subagent.registry",
        "agent_definition_to_factory",
    ),
    "load_project_skills": (".skills.skill", "load_project_skills"),
    "load_skills_from_dir": (".skills.skill", "load_skills_from_dir"),
    "load_user_skills": (".skills.skill", "load_user_skills"),
    "page_iterator": (".utils.paging", "page_iterator"),
}


def __getattr__(name: str) -> Any:
    return import_lazy_symbol(__name__, globals(), _LAZY_IMPORTS, name)


def __dir__() -> list[str]:
    return lazy_dir(globals(), __all__)
