---
name: OpenHands PR Review
description: Automated PR review using OpenHands agent
author: OpenHands

branding:
    icon: code
    color: blue

inputs:
    mode:
        description: "Review mode: 'sdk' runs locally, 'cloud' launches in OpenHands Cloud"
        required: false
        default: sdk
    llm-model:
        description: LLM model to use (only for sdk mode, ignored in cloud mode)
        required: false
        default: anthropic/claude-sonnet-4-5-20250929
    llm-base-url:
        description: LLM base URL (only for sdk mode, ignored in cloud mode)
        required: false
        default: ''
    review-style:
        description: "Review style: 'standard' or 'roasted'"
        required: false
        default: standard
    sdk-version:
        description: SDK version tag or branch name to use (e.g., v1.0.0 or main)
        required: false
        default: main
    use-pr-branch-for-sdk:
        description: When true and reviewing a PR on the SDK repo itself, use the PR's head branch instead of sdk-version
        required: false
        default: 'false'
    llm-api-key:
        description: LLM API key (required for sdk mode)
        required: false
    openhands-cloud-api-key:
        description: OpenHands Cloud API key (required for cloud mode)
        required: false
    github-token:
        description: GitHub token for API access (required for sdk mode; not required for cloud mode if your OpenHands Cloud account has access to the
            repo)
        required: false

runs:
    using: composite
    steps:
        - name: Determine SDK ref to use
          id: sdk-ref
          shell: bash
          run: |
              # If use-pr-branch-for-sdk is true and we're reviewing a PR on the SDK repo itself,
              # use the PR's head branch instead of the sdk-version input
              if [ "${{ inputs.use-pr-branch-for-sdk }}" = "true" ] && [ "${{ github.repository }}" = "OpenHands/software-agent-sdk" ]; then
                echo "ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
                echo "Using PR branch '${{ github.event.pull_request.head.ref }}' for SDK (reviewing SDK repo PR)"
              else
                echo "ref=${{ inputs.sdk-version }}" >> $GITHUB_OUTPUT
                echo "Using sdk-version '${{ inputs.sdk-version }}' for SDK"
              fi

        - name: Checkout software-agent-sdk repository
          uses: actions/checkout@v4
          with:
              repository: OpenHands/software-agent-sdk
              ref: ${{ steps.sdk-ref.outputs.ref }}
              path: software-agent-sdk

        - name: Checkout PR repository
          uses: actions/checkout@v4
          with:
              repository: ${{ github.event.pull_request.head.repo.full_name }}
              ref: ${{ github.event.pull_request.head.ref }}
              fetch-depth: 0
              persist-credentials: false
              path: pr-repo

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
              python-version: '3.13'

        - name: Install uv
          uses: astral-sh/setup-uv@v6
          with:
              enable-cache: true

        - name: Install GitHub CLI
          shell: bash
          run: |
              sudo apt-get update
              sudo apt-get install -y gh

        - name: Install OpenHands dependencies
          shell: bash
          run: |
              uv pip install --system ./software-agent-sdk/openhands-sdk ./software-agent-sdk/openhands-tools ./software-agent-sdk/openhands-workspace

        - name: Check required configuration
          shell: bash
          env:
              MODE: ${{ inputs.mode }}
              LLM_API_KEY: ${{ inputs.llm-api-key }}
              OPENHANDS_CLOUD_API_KEY: ${{ inputs.openhands-cloud-api-key }}
              GITHUB_TOKEN: ${{ inputs.github-token }}
          run: |
              if [ "$MODE" = "sdk" ]; then
                if [ -z "$LLM_API_KEY" ]; then
                  echo "Error: llm-api-key is required for 'sdk' mode."
                  exit 1
                fi
                if [ -z "$GITHUB_TOKEN" ]; then
                  echo "Error: github-token is required for 'sdk' mode."
                  exit 1
                fi
              elif [ "$MODE" = "cloud" ]; then
                if [ -z "$OPENHANDS_CLOUD_API_KEY" ]; then
                  echo "Error: openhands-cloud-api-key is required for 'cloud' mode."
                  exit 1
                fi
                # Note: github-token is not required for cloud mode if your OpenHands Cloud account has access to the repo
              fi

              echo "PR Number: ${{ github.event.pull_request.number }}"
              echo "PR Title: ${{ github.event.pull_request.title }}"
              echo "Repository: ${{ github.repository }}"
              echo "Mode: $MODE"
              echo "SDK Version: ${{ inputs.sdk-version }}"
              if [ "$MODE" = "sdk" ]; then
                echo "LLM model: ${{ inputs.llm-model }}"
                if [ -n "${{ inputs.llm-base-url }}" ]; then
                  echo "LLM base URL: ${{ inputs.llm-base-url }}"
                fi
              else
                echo "Note: LLM_MODEL and LLM_BASE_URL are ignored in cloud mode"
                if [ -z "$GITHUB_TOKEN" ]; then
                  echo "Note: github-token not provided; OpenHands Cloud will use its own repo access"
                fi
              fi

        - name: Run PR review
          shell: bash
          env:
              MODE: ${{ inputs.mode }}
              LLM_MODEL: ${{ inputs.llm-model }}
              LLM_BASE_URL: ${{ inputs.llm-base-url }}
              REVIEW_STYLE: ${{ inputs.review-style }}
              LLM_API_KEY: ${{ inputs.llm-api-key }}
              GITHUB_TOKEN: ${{ inputs.github-token }}
              OPENHANDS_CLOUD_API_KEY: ${{ inputs.openhands-cloud-api-key }}
              PR_NUMBER: ${{ github.event.pull_request.number }}
              PR_TITLE: ${{ github.event.pull_request.title }}
              PR_BODY: ${{ github.event.pull_request.body }}
              PR_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
              PR_HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
              REPO_NAME: ${{ github.repository }}
          run: |
              cd pr-repo
              uv run python ../software-agent-sdk/examples/03_github_workflows/02_pr_review/agent_script.py

        - name: Upload logs as artifact
          uses: actions/upload-artifact@v4
          if: always()
          with:
              name: openhands-pr-review-logs
              path: |
                  *.log
                  output/
              retention-days: 7
