from .classifier import (
    is_content_policy_violation,
    is_context_window_exceeded,
    is_prompt_cache_too_small,
    is_quota_exhaustion_error,
    looks_like_auth_error,
    looks_like_malformed_conversation_history_error,
)
from .mapping import map_provider_exception
from .types import (
    FunctionCallConversionError,
    FunctionCallNotExistsError,
    FunctionCallValidationError,
    LLMAuthenticationError,
    LLMBadRequestError,
    LLMBudgetExceededError,
    LLMContentPolicyViolationError,
    LLMContextWindowExceedError,
    LLMContextWindowTooSmallError,
    LLMError,
    LLMMalformedActionError,
    LLMMalformedConversationHistoryError,
    LLMNoActionError,
    LLMNoResponseError,
    LLMRateLimitError,
    LLMResponseError,
    LLMServiceUnavailableError,
    LLMTimeoutError,
    OperationCancelled,
    UserCancelledError,
)


__all__ = [
    # Types
    "LLMError",
    "LLMMalformedActionError",
    "LLMNoActionError",
    "LLMResponseError",
    "FunctionCallConversionError",
    "FunctionCallValidationError",
    "FunctionCallNotExistsError",
    "LLMNoResponseError",
    "LLMContextWindowExceedError",
    "LLMMalformedConversationHistoryError",
    "LLMContextWindowTooSmallError",
    "LLMContentPolicyViolationError",
    "LLMAuthenticationError",
    "LLMRateLimitError",
    "LLMTimeoutError",
    "LLMServiceUnavailableError",
    "LLMBadRequestError",
    "LLMBudgetExceededError",
    "UserCancelledError",
    "OperationCancelled",
    # Helpers
    "is_content_policy_violation",
    "is_context_window_exceeded",
    "is_prompt_cache_too_small",
    "is_quota_exhaustion_error",
    "looks_like_auth_error",
    "looks_like_malformed_conversation_history_error",
    "map_provider_exception",
]
