---
name: TypeScript client release

on:
    push:
        branches: [main]

jobs:
    release-please:
        permissions:
            contents: write
            pull-requests: write
        secrets: inherit
        uses: OpenHands/release-actions/.github/workflows/release-please.yml@main
        with:
            config-file: .github/release-please/typescript-client-config.json
            manifest-file: .github/release-please/typescript-client-manifest.json
            github-scoped-notes: true
